### PR TITLE
Minor text correction

### PR DESCRIPTION
**Pull request by mariozig**
Thanks for putting this out there! 

I'm going through it in preparation for AppAcademy in a few weeks and I noticed this minor inconsistency between the instructions and the actual tests.

### CODE REVIEW

**Comment by alexch** [comment]
I'll put this in, but in the future, could you make PRs on http://github.com/ultrasaurus/test-first-teaching ?

**Comment by mariozig** [comment]
:) Yes absolutely.  I actually wasn't aware that existed.  It will save you any hassle let me know -- I'm happy to submit this same change over there. 

Thanks alex!

**Comment by alexch** [comment]
No prob, I already did it. And I just added this line to the (generated) instructions:

> If you want to submit a patch or a solution, please fork the [Test-First Teaching](http://github.com/ultrasaurus/test-first-teaching) repo and submit a Pull Request from there.

Of course, most people still won't read it, but short of a much more clever git-based solution, I think that's all I can do.

Also, check out my site http://CodeLikeThis.com for related notes and videos.

**Comment by mariozig** [comment]
Thanks!! I'll definitely be checking out the RSpec and JS lessons!

**Pull request closed without merging**
