### PR TITLE
Update Gemfile to specify RSpec 2: specs aren't RSpec 3 compatible

### PR DESCRIPTION
**Pull request by ruggeri**
And that's okay :-)

### CODE REVIEW

**Comment by ruggeri** [comment]
This would be a nice contribution to merge, the specs for the dictionary exercise fail because RSpec 3 doesn't want you to use `_be_false` anymore. The Gemfile used to specify RSpec `>=2.0`, which means 3.0 will be used if it is installed. This fix allows one to run

```
bundle exec rake
```

and have things work :-)

**Comment by Supernats** [comment]
:+1:  I just helped out a friend who had banging his head against this for far too long.

**Comment by ruggeri** [comment]
In the meantime, you can direct people to my fork of the project: https://github.com/appacademy/test-first-ruby

**Comment by alexch** [comment]
whoops, lost this in the queue. Just merged! 

Also needs to be in the main test-first-teaching repo since this repo is automatically generated. https://github.com/ultrasaurus/test-first-teaching/blob/master/Gemfile already has ~>2.10 ...  done: https://github.com/ultrasaurus/test-first-teaching/commit/d888bfecaf23c88c78da06611c03f7719bd24591

**Pull request merged**
